# Generated by Django 5.1.4 on 2025-08-27 13:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('open_day', 'Open Day'), ('workshop', 'Workshop'), ('parent_meeting', 'Parent Meeting'), ('community', 'Community Event'), ('training', 'Training')], max_length=20)),
                ('description', ckeditor.fields.RichTextField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('is_all_day', models.BooleanField(default=False)),
                ('location', models.CharField(default='Forest School Cyprus, Kornos', max_length=300)),
                ('location_details', models.TextField(blank=True)),
                ('requires_registration', models.BooleanField(default=False)),
                ('max_participants', models.IntegerField(blank=True, null=True)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, upload_to='events/')),
                ('is_published', models.BooleanField(default=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
    ]
