# Generated by Django 5.1.4 on 2025-08-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('volunteer_type', models.CharField(choices=[('plain', 'Plain Volunteering'), ('teaching', 'Teaching Volunteering'), ('technical', 'Technical Volunteering'), ('other', 'Other')], help_text='Select the type of volunteering you are interested in.', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
