# Generated by Django 5.1.4 on 2025-08-27 13:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('pedagogue', 'Pedagogue'), ('coordinator', 'Program Coordinator'), ('volunteer', 'Volunteer'), ('director', 'Director'), ('assistant', 'Assistant')], max_length=20)),
                ('title_greek', models.CharField(blank=True, help_text='Title in Greek', max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='team/')),
                ('bio', ckeditor.fields.RichTextField(help_text='Professional biography')),
                ('qualifications', ckeditor.fields.RichTextField(blank=True)),
                ('specialties', models.CharField(blank=True, help_text='Areas of expertise', max_length=300)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on main team page')),
                ('display_order', models.IntegerField(default=0, help_text='Order of appearance')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['display_order', 'last_name'],
            },
        ),
    ]
