# Generated by Django 5.1.4 on 2025-08-27 13:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, upload_to='home/')),
                ('hero_title', models.CharField(default='Welcome to Forest School Cyprus', max_length=200)),
                ('hero_subtitle', models.TextField(default='Where children grow, learn, and thrive in nature.')),
                ('years_operating', models.IntegerField(default=7, help_text='Years in operation')),
                ('children_served', models.IntegerField(default=200, help_text='Total children served')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page Content',
                'verbose_name_plural': 'Home Page Content',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Forest School Cyprus', max_length=200)),
                ('tagline', models.CharField(default='Where children grow, learn, and thrive in nature.', max_length=300)),
                ('phone', models.CharField(default='+357 9980 3654', max_length=20)),
                ('email', models.EmailField(default='forestschool.cy@gmail.com', max_length=254)),
                ('address', models.TextField(default='Agiou Alexandrou Street, Kornos')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('vision_text', ckeditor.fields.RichTextField()),
                ('who_we_are_text', ckeditor.fields.RichTextField()),
                ('why_choose_us_text', ckeditor.fields.RichTextField()),
                ('feature_immersive', models.CharField(default='An immersive, nature-based learning experience', max_length=200)),
                ('feature_outdoor', models.CharField(default='100% outdoor, inquiry-driven, and child-led learning', max_length=200)),
                ('feature_building', models.CharField(default='Building confidence, resilience, and environmental stewardship', max_length=200)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
