# Generated by Django 5.1.4 on 2025-08-27 13:13

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('program_type', models.CharField(choices=[('morning', 'Morning School'), ('afternoon', 'Afternoon Program'), ('weekend', 'Weekend Program'), ('camp', 'Holiday Camp')], max_length=20)),
                ('age_group', models.CharField(choices=[('2-3', '2-3 years'), ('3-6', '3-6 years'), ('4-10', '4-10 years'), ('mixed', 'Mixed ages')], max_length=10)),
                ('description', ckeditor.fields.RichTextField()),
                ('schedule', models.CharField(help_text='e.g., 8:00 AM - 2:30 PM', max_length=200)),
                ('is_flexible_pricing', models.BooleanField(default=True)),
                ('includes_meals', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['program_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PricingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., 5 days/week', max_length=100)),
                ('days_per_week', models.IntegerField()),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('daily_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_options', to='contact.program')),
            ],
            options={
                'ordering': ['-days_per_week'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('child_name', models.CharField(blank=True, max_length=200)),
                ('child_age', models.IntegerField(blank=True, null=True)),
                ('inquiry_type', models.CharField(choices=[('admission', 'Admission Inquiry'), ('general', 'General Information'), ('volunteer', 'Volunteering'), ('partnership', 'Partnership'), ('media', 'Media Inquiry')], max_length=20)),
                ('message', models.TextField()),
                ('is_responded', models.BooleanField(default=False)),
                ('response_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('program_interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.program')),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
