# Generated by Django 5.1.4 on 2025-09-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteerapplication',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='volunteer_type',
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='role',
            field=models.CharField(choices=[('plain', 'Plain Volunteering'), ('teaching', 'Teaching Volunteering'), ('technical', 'Technical Volunteering'), ('other', 'Other')], default='plain', max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='message',
            field=models.TextField(),
        ),
    ]
