# Generated by Django 5.1.4 on 2025-08-27 13:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('season', models.CharField(choices=[('easter', 'Easter Camp'), ('summer', 'Summer Camp'), ('christmas', 'Christmas Camp'), ('special', 'Special Event')], max_length=20)),
                ('year', models.IntegerField()),
                ('description', ckeditor.fields.RichTextField()),
                ('activities', ckeditor.fields.RichTextField(help_text='List of activities and features')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('daily_schedule', models.CharField(blank=True, max_length=200)),
                ('age_group', models.CharField(default='4-10 years', max_length=100)),
                ('max_participants', models.IntegerField(default=20)),
                ('current_enrollment', models.IntegerField(default=0)),
                ('daily_fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weekly_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('featured_image', models.ImageField(blank=True, upload_to='camps/')),
                ('is_open_for_registration', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', '-start_date'],
                'unique_together': {('season', 'year')},
            },
        ),
    ]
