# Generated by Django 5.1.4 on 2025-09-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age_range', models.CharField(max_length=50)),
                ('daily_hours', models.CharField(max_length=100)),
                ('week_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('sleepover_option', models.BooleanField(default=False)),
                ('sleepover_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('registration_open', models.DateField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'start_date'],
            },
        ),
    ]
